package pe.edu.unsch.entities;
// Generated 12/07/2019 10:22:58 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Cargaacademica generated by hbm2java
 */
@Entity
@Table(name = "cargaacademica", catalog = "cargabd")
public class Cargaacademica implements java.io.Serializable {

	private Integer id_carga_academica;
	private Curso curso;
	private Docente docente;
	private String semestre_academico;

	private String nombre;
	private long horas;

	@Transient
	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Transient
	public long getHoras() {
		return horas;
	}

	public void setHoras(long horas) {
		this.horas = horas;
	}

	public Cargaacademica() {
	}

	public Cargaacademica(Curso curso, Docente docente, String semestre_academico) {
		this.curso = curso;
		this.docente = docente;
		this.semestre_academico = semestre_academico;
	}

	public Cargaacademica(String nombre, long horas, String semestre_academico) {
		this.nombre = nombre;
		this.horas = horas;
		this.semestre_academico = semestre_academico;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_carga_academica", unique = true, nullable = false)
	public Integer getId_carga_academica() {
		return this.id_carga_academica;
	}

	public void setId_carga_academica(Integer id_carga_academica) {
		this.id_carga_academica = id_carga_academica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_curso")
	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_docente")
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Column(name = "semestre_academico", length = 10)
	public String getSemestre_academico() {
		return this.semestre_academico;
	}

	public void setSemestre_academico(String semestre_academico) {
		this.semestre_academico = semestre_academico;
	}

}
