package pe.edu.unsch.entities;
// Generated 12/07/2a019 10:22:58 AM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "curso", catalog = "cargabd")
public class Curso implements java.io.Serializable {

	private Integer id_curso;
	private String nombre_curso;
	private int horas_semanales;
	private Set<Cargaacademica> cargaacademicas = new HashSet<Cargaacademica>(0);

	public Curso() {
	}

	public Curso(String nombre_curso, int horas_semanales) {
		this.nombre_curso = nombre_curso;
		this.horas_semanales = horas_semanales;
	}

	public Curso(String nombre_curso, int horas_semanales, Set<Cargaacademica> cargaacademicas) {
		this.nombre_curso = nombre_curso;
		this.horas_semanales = horas_semanales;
		this.cargaacademicas = cargaacademicas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_curso", unique = true, nullable = false)
	public Integer getId_curso() {
		return this.id_curso;
	}

	public void setId_curso(Integer id_curso) {
		this.id_curso = id_curso;
	}

	@Column(name = "nombre_curso", nullable = false, length = 50)
	public String getNombre_curso() {
		return this.nombre_curso;
	}

	public void setNombre_curso(String nombre_curso) {
		this.nombre_curso = nombre_curso;
	}

	@Column(name = "horas_semanales", nullable = false)
	public int getHoras_semanales() {
		return this.horas_semanales;
	}

	public void setHoras_semanales(int horas_semanales) {
		this.horas_semanales = horas_semanales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "curso")
	public Set<Cargaacademica> getCargaacademicas() {
		return this.cargaacademicas;
	}

	public void setCargaacademicas(Set<Cargaacademica> cargaacademicas) {
		this.cargaacademicas = cargaacademicas;
	}

}
