package pe.edu.unsch.entities;
// Generated 12/07/2019 10:22:58 AM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", catalog = "cargabd")
public class Docente implements java.io.Serializable {

	private Integer id_docente;
	private String nombre;
	private String apellidos;
	private Set<Cargaacademica> cargaacademicas = new HashSet<Cargaacademica>(0);

	public Docente() {
	}

	public Docente(String nombre, String apellidos) {
		this.nombre = nombre;
		this.apellidos = apellidos;
	}

	public Docente(String nombre, String apellidos, Set<Cargaacademica> cargaacademicas) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.cargaacademicas = cargaacademicas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_docente", unique = true, nullable = false)
	public Integer getId_docente() {
		return this.id_docente;
	}

	public void setId_docente(Integer id_docente) {
		this.id_docente = id_docente;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidos", nullable = false, length = 50)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
	public Set<Cargaacademica> getCargaacademicas() {
		return this.cargaacademicas;
	}

	public void setCargaacademicas(Set<Cargaacademica> cargaacademicas) {
		this.cargaacademicas = cargaacademicas;
	}

}
